use_frameworks!

target 'DirectoryObserver_Example' do
  pod 'DirectoryObserver', :path => '../'

  target 'DirectoryObserver_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
